name: pipeline

on:
  push:
    branches:
      - Iza
  pull_request:
    branches:
      - Iza
jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install
        working-directory: backend

      - name: Run build
        run: npm run build
        working-directory: backend

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: pacote-build
          path: backend

  test:
    name: Running unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install
        working-directory: backend

      - name: Run unit tests
        run: npm run test
        working-directory: backend

      - name: Generate test coverage report
        run: npm run test -- --coverage
        working-directory: backend

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: backend/coverage
